default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-added-large-files
        exclude_types: ['gzip', 'jupyter']
        args: ['--maxkb=2048']
    -   id: end-of-file-fixer
